#!/bin/bash

function upgrade() {
    # Get the directory the project has been cloned into
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    # Ensure we are in the correct directory
    cd $DIR
    git pull
    pip install -r requirements.txt
    if [ -L "ns_api" ]; then
        # Remove obsolete symlink as nsapi is installed through pip now
        rm "ns_api"
        echo "Removed old symlink"
    fi
    python ns_notifications.py updated
}

if [[ -z "$VIRTUAL_ENV" ]]; then
    # Only activate the virtualenv if we aren't in one already
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    workon ns-notifications
fi

if [ -f needs_updating ]; then
    # Upgrade needed
    upgrade
    rm needs_updating
fi

if [ -z "$1" ]; then
    python ns_notifications.py run_all_notifications
#elif [ "$1" == "clearpb" ]; then
#    python ns_notifications.py clear_pushbullet
elif [ "$1" == "upgrade" ]; then
    upgrade
elif [ "$1" == "update" ]; then
    upgrade
elif [ "$1" == "help" ]; then
    python ns_notifications.py
else
    python ns_notifications.py $1
fi
