#!/bin/bash

python -c 'import sys; print(sys.real_prefix)' 2>/dev/null && INVENV=1 || INVENV=0

if [ $INVENV == 0 ]; then
    # Only activate the virtualenv if we aren't in one already
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    workon ns-notifications
fi

if [ -z "$1" ]; then
    python ns_notifications.py run_all_notifications
#elif [ "$1" == "clearpb" ]; then
#    python ns_notifications.py clear_pushbullet
elif [ "$1" == "upgrade" ]; then
    git pull
    pip install -r requirements.txt
    python ns_notifications.py updated
elif [ "$1" == "help" ]; then
    python ns_notifications.py
else
    python ns_notifications.py $1
fi
